// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package aelf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionResultStatus int32

const (
	TransactionResultStatus_NOT_EXISTED            TransactionResultStatus = 0
	TransactionResultStatus_PENDING                TransactionResultStatus = 1
	TransactionResultStatus_FAILED                 TransactionResultStatus = 2
	TransactionResultStatus_MINED                  TransactionResultStatus = 3
	TransactionResultStatus_CONFLICT               TransactionResultStatus = 4
	TransactionResultStatus_PENDING_VALIDATION     TransactionResultStatus = 5
	TransactionResultStatus_NODE_VALIDATION_FAILED TransactionResultStatus = 6
)

var TransactionResultStatus_name = map[int32]string{
	0: "NOT_EXISTED",
	1: "PENDING",
	2: "FAILED",
	3: "MINED",
	4: "CONFLICT",
	5: "PENDING_VALIDATION",
	6: "NODE_VALIDATION_FAILED",
}

var TransactionResultStatus_value = map[string]int32{
	"NOT_EXISTED":            0,
	"PENDING":                1,
	"FAILED":                 2,
	"MINED":                  3,
	"CONFLICT":               4,
	"PENDING_VALIDATION":     5,
	"NODE_VALIDATION_FAILED": 6,
}

func (x TransactionResultStatus) String() string {
	return proto.EnumName(TransactionResultStatus_name, int32(x))
}

func (TransactionResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

type Transaction struct {
	From                 *Address `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Address `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	RefBlockNumber       int64    `protobuf:"varint,3,opt,name=ref_block_number,json=refBlockNumber,proto3" json:"ref_block_number,omitempty"`
	RefBlockPrefix       []byte   `protobuf:"bytes,4,opt,name=ref_block_prefix,json=refBlockPrefix,proto3" json:"ref_block_prefix,omitempty"`
	MethodName           string   `protobuf:"bytes,5,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Params               []byte   `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`
	Signature            []byte   `protobuf:"bytes,10000,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetFrom() *Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() *Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetRefBlockNumber() int64 {
	if m != nil {
		return m.RefBlockNumber
	}
	return 0
}

func (m *Transaction) GetRefBlockPrefix() []byte {
	if m != nil {
		return m.RefBlockPrefix
	}
	return nil
}

func (m *Transaction) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *Transaction) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Transaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type StatePath struct {
	Parts                []string `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatePath) Reset()         { *m = StatePath{} }
func (m *StatePath) String() string { return proto.CompactTextString(m) }
func (*StatePath) ProtoMessage()    {}
func (*StatePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *StatePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatePath.Unmarshal(m, b)
}
func (m *StatePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatePath.Marshal(b, m, deterministic)
}
func (m *StatePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatePath.Merge(m, src)
}
func (m *StatePath) XXX_Size() int {
	return xxx_messageInfo_StatePath.Size(m)
}
func (m *StatePath) XXX_DiscardUnknown() {
	xxx_messageInfo_StatePath.DiscardUnknown(m)
}

var xxx_messageInfo_StatePath proto.InternalMessageInfo

func (m *StatePath) GetParts() []string {
	if m != nil {
		return m.Parts
	}
	return nil
}

type ScopedStatePath struct {
	Address              *Address   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Path                 *StatePath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ScopedStatePath) Reset()         { *m = ScopedStatePath{} }
func (m *ScopedStatePath) String() string { return proto.CompactTextString(m) }
func (*ScopedStatePath) ProtoMessage()    {}
func (*ScopedStatePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

func (m *ScopedStatePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScopedStatePath.Unmarshal(m, b)
}
func (m *ScopedStatePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScopedStatePath.Marshal(b, m, deterministic)
}
func (m *ScopedStatePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScopedStatePath.Merge(m, src)
}
func (m *ScopedStatePath) XXX_Size() int {
	return xxx_messageInfo_ScopedStatePath.Size(m)
}
func (m *ScopedStatePath) XXX_DiscardUnknown() {
	xxx_messageInfo_ScopedStatePath.DiscardUnknown(m)
}

var xxx_messageInfo_ScopedStatePath proto.InternalMessageInfo

func (m *ScopedStatePath) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ScopedStatePath) GetPath() *StatePath {
	if m != nil {
		return m.Path
	}
	return nil
}

type TransactionResult struct {
	TransactionId        *Hash                   `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status               TransactionResultStatus `protobuf:"varint,2,opt,name=status,proto3,enum=aelf.TransactionResultStatus" json:"status,omitempty"`
	Logs                 []*LogEvent             `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	Bloom                []byte                  `protobuf:"bytes,4,opt,name=bloom,proto3" json:"bloom,omitempty"`
	ReturnValue          []byte                  `protobuf:"bytes,5,opt,name=return_value,json=returnValue,proto3" json:"return_value,omitempty"`
	BlockNumber          int64                   `protobuf:"varint,6,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash            *Hash                   `protobuf:"bytes,7,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Error                string                  `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TransactionResult) Reset()         { *m = TransactionResult{} }
func (m *TransactionResult) String() string { return proto.CompactTextString(m) }
func (*TransactionResult) ProtoMessage()    {}
func (*TransactionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{3}
}

func (m *TransactionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResult.Unmarshal(m, b)
}
func (m *TransactionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResult.Marshal(b, m, deterministic)
}
func (m *TransactionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResult.Merge(m, src)
}
func (m *TransactionResult) XXX_Size() int {
	return xxx_messageInfo_TransactionResult.Size(m)
}
func (m *TransactionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResult.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResult proto.InternalMessageInfo

func (m *TransactionResult) GetTransactionId() *Hash {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

func (m *TransactionResult) GetStatus() TransactionResultStatus {
	if m != nil {
		return m.Status
	}
	return TransactionResultStatus_NOT_EXISTED
}

func (m *TransactionResult) GetLogs() []*LogEvent {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *TransactionResult) GetBloom() []byte {
	if m != nil {
		return m.Bloom
	}
	return nil
}

func (m *TransactionResult) GetReturnValue() []byte {
	if m != nil {
		return m.ReturnValue
	}
	return nil
}

func (m *TransactionResult) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *TransactionResult) GetBlockHash() *Hash {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *TransactionResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LogEvent struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Indexed              [][]byte `protobuf:"bytes,3,rep,name=indexed,proto3" json:"indexed,omitempty"`
	NonIndexed           []byte   `protobuf:"bytes,4,opt,name=non_indexed,json=nonIndexed,proto3" json:"non_indexed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEvent) Reset()         { *m = LogEvent{} }
func (m *LogEvent) String() string { return proto.CompactTextString(m) }
func (*LogEvent) ProtoMessage()    {}
func (*LogEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{4}
}

func (m *LogEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEvent.Unmarshal(m, b)
}
func (m *LogEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEvent.Marshal(b, m, deterministic)
}
func (m *LogEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEvent.Merge(m, src)
}
func (m *LogEvent) XXX_Size() int {
	return xxx_messageInfo_LogEvent.Size(m)
}
func (m *LogEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LogEvent proto.InternalMessageInfo

func (m *LogEvent) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *LogEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogEvent) GetIndexed() [][]byte {
	if m != nil {
		return m.Indexed
	}
	return nil
}

func (m *LogEvent) GetNonIndexed() []byte {
	if m != nil {
		return m.NonIndexed
	}
	return nil
}

type SmartContractRegistration struct {
	Category             int32    `protobuf:"zigzag32,1,opt,name=category,proto3" json:"category,omitempty"`
	Code                 []byte   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	CodeHash             *Hash    `protobuf:"bytes,3,opt,name=code_hash,json=codeHash,proto3" json:"code_hash,omitempty"`
	IsSystemContract     bool     `protobuf:"varint,4,opt,name=is_system_contract,json=isSystemContract,proto3" json:"is_system_contract,omitempty"`
	Version              int32    `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartContractRegistration) Reset()         { *m = SmartContractRegistration{} }
func (m *SmartContractRegistration) String() string { return proto.CompactTextString(m) }
func (*SmartContractRegistration) ProtoMessage()    {}
func (*SmartContractRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{5}
}

func (m *SmartContractRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartContractRegistration.Unmarshal(m, b)
}
func (m *SmartContractRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartContractRegistration.Marshal(b, m, deterministic)
}
func (m *SmartContractRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartContractRegistration.Merge(m, src)
}
func (m *SmartContractRegistration) XXX_Size() int {
	return xxx_messageInfo_SmartContractRegistration.Size(m)
}
func (m *SmartContractRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartContractRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_SmartContractRegistration proto.InternalMessageInfo

func (m *SmartContractRegistration) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *SmartContractRegistration) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *SmartContractRegistration) GetCodeHash() *Hash {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *SmartContractRegistration) GetIsSystemContract() bool {
	if m != nil {
		return m.IsSystemContract
	}
	return false
}

func (m *SmartContractRegistration) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type TransactionExecutingStateSet struct {
	Writes               map[string][]byte `protobuf:"bytes,1,rep,name=writes,proto3" json:"writes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Reads                map[string]bool   `protobuf:"bytes,2,rep,name=reads,proto3" json:"reads,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Deletes              map[string]bool   `protobuf:"bytes,3,rep,name=deletes,proto3" json:"deletes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransactionExecutingStateSet) Reset()         { *m = TransactionExecutingStateSet{} }
func (m *TransactionExecutingStateSet) String() string { return proto.CompactTextString(m) }
func (*TransactionExecutingStateSet) ProtoMessage()    {}
func (*TransactionExecutingStateSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{6}
}

func (m *TransactionExecutingStateSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionExecutingStateSet.Unmarshal(m, b)
}
func (m *TransactionExecutingStateSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionExecutingStateSet.Marshal(b, m, deterministic)
}
func (m *TransactionExecutingStateSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionExecutingStateSet.Merge(m, src)
}
func (m *TransactionExecutingStateSet) XXX_Size() int {
	return xxx_messageInfo_TransactionExecutingStateSet.Size(m)
}
func (m *TransactionExecutingStateSet) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionExecutingStateSet.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionExecutingStateSet proto.InternalMessageInfo

func (m *TransactionExecutingStateSet) GetWrites() map[string][]byte {
	if m != nil {
		return m.Writes
	}
	return nil
}

func (m *TransactionExecutingStateSet) GetReads() map[string]bool {
	if m != nil {
		return m.Reads
	}
	return nil
}

func (m *TransactionExecutingStateSet) GetDeletes() map[string]bool {
	if m != nil {
		return m.Deletes
	}
	return nil
}

type Address struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{7}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Hash struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hash) Reset()         { *m = Hash{} }
func (m *Hash) String() string { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()    {}
func (*Hash) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{8}
}

func (m *Hash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hash.Unmarshal(m, b)
}
func (m *Hash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hash.Marshal(b, m, deterministic)
}
func (m *Hash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hash.Merge(m, src)
}
func (m *Hash) XXX_Size() int {
	return xxx_messageInfo_Hash.Size(m)
}
func (m *Hash) XXX_DiscardUnknown() {
	xxx_messageInfo_Hash.DiscardUnknown(m)
}

var xxx_messageInfo_Hash proto.InternalMessageInfo

func (m *Hash) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SInt32Value struct {
	Value                int32    `protobuf:"zigzag32,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SInt32Value) Reset()         { *m = SInt32Value{} }
func (m *SInt32Value) String() string { return proto.CompactTextString(m) }
func (*SInt32Value) ProtoMessage()    {}
func (*SInt32Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{9}
}

func (m *SInt32Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SInt32Value.Unmarshal(m, b)
}
func (m *SInt32Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SInt32Value.Marshal(b, m, deterministic)
}
func (m *SInt32Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SInt32Value.Merge(m, src)
}
func (m *SInt32Value) XXX_Size() int {
	return xxx_messageInfo_SInt32Value.Size(m)
}
func (m *SInt32Value) XXX_DiscardUnknown() {
	xxx_messageInfo_SInt32Value.DiscardUnknown(m)
}

var xxx_messageInfo_SInt32Value proto.InternalMessageInfo

func (m *SInt32Value) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type SInt64Value struct {
	Value                int64    `protobuf:"zigzag64,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SInt64Value) Reset()         { *m = SInt64Value{} }
func (m *SInt64Value) String() string { return proto.CompactTextString(m) }
func (*SInt64Value) ProtoMessage()    {}
func (*SInt64Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{10}
}

func (m *SInt64Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SInt64Value.Unmarshal(m, b)
}
func (m *SInt64Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SInt64Value.Marshal(b, m, deterministic)
}
func (m *SInt64Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SInt64Value.Merge(m, src)
}
func (m *SInt64Value) XXX_Size() int {
	return xxx_messageInfo_SInt64Value.Size(m)
}
func (m *SInt64Value) XXX_DiscardUnknown() {
	xxx_messageInfo_SInt64Value.DiscardUnknown(m)
}

var xxx_messageInfo_SInt64Value proto.InternalMessageInfo

func (m *SInt64Value) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type MerklePath struct {
	MerklePathNodes      []*MerklePathNode `protobuf:"bytes,1,rep,name=merkle_path_nodes,json=merklePathNodes,proto3" json:"merkle_path_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MerklePath) Reset()         { *m = MerklePath{} }
func (m *MerklePath) String() string { return proto.CompactTextString(m) }
func (*MerklePath) ProtoMessage()    {}
func (*MerklePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{11}
}

func (m *MerklePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerklePath.Unmarshal(m, b)
}
func (m *MerklePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerklePath.Marshal(b, m, deterministic)
}
func (m *MerklePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerklePath.Merge(m, src)
}
func (m *MerklePath) XXX_Size() int {
	return xxx_messageInfo_MerklePath.Size(m)
}
func (m *MerklePath) XXX_DiscardUnknown() {
	xxx_messageInfo_MerklePath.DiscardUnknown(m)
}

var xxx_messageInfo_MerklePath proto.InternalMessageInfo

func (m *MerklePath) GetMerklePathNodes() []*MerklePathNode {
	if m != nil {
		return m.MerklePathNodes
	}
	return nil
}

type MerklePathNode struct {
	Hash                 *Hash    `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	IsLeftChildNode      bool     `protobuf:"varint,2,opt,name=is_left_child_node,json=isLeftChildNode,proto3" json:"is_left_child_node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerklePathNode) Reset()         { *m = MerklePathNode{} }
func (m *MerklePathNode) String() string { return proto.CompactTextString(m) }
func (*MerklePathNode) ProtoMessage()    {}
func (*MerklePathNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{12}
}

func (m *MerklePathNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerklePathNode.Unmarshal(m, b)
}
func (m *MerklePathNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerklePathNode.Marshal(b, m, deterministic)
}
func (m *MerklePathNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerklePathNode.Merge(m, src)
}
func (m *MerklePathNode) XXX_Size() int {
	return xxx_messageInfo_MerklePathNode.Size(m)
}
func (m *MerklePathNode) XXX_DiscardUnknown() {
	xxx_messageInfo_MerklePathNode.DiscardUnknown(m)
}

var xxx_messageInfo_MerklePathNode proto.InternalMessageInfo

func (m *MerklePathNode) GetHash() *Hash {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *MerklePathNode) GetIsLeftChildNode() bool {
	if m != nil {
		return m.IsLeftChildNode
	}
	return false
}

type BinaryMerkleTree struct {
	Nodes                []*Hash  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Root                 *Hash    `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	LeafCount            int32    `protobuf:"varint,3,opt,name=leaf_count,json=leafCount,proto3" json:"leaf_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinaryMerkleTree) Reset()         { *m = BinaryMerkleTree{} }
func (m *BinaryMerkleTree) String() string { return proto.CompactTextString(m) }
func (*BinaryMerkleTree) ProtoMessage()    {}
func (*BinaryMerkleTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{13}
}

func (m *BinaryMerkleTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinaryMerkleTree.Unmarshal(m, b)
}
func (m *BinaryMerkleTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinaryMerkleTree.Marshal(b, m, deterministic)
}
func (m *BinaryMerkleTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryMerkleTree.Merge(m, src)
}
func (m *BinaryMerkleTree) XXX_Size() int {
	return xxx_messageInfo_BinaryMerkleTree.Size(m)
}
func (m *BinaryMerkleTree) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryMerkleTree.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryMerkleTree proto.InternalMessageInfo

func (m *BinaryMerkleTree) GetNodes() []*Hash {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *BinaryMerkleTree) GetRoot() *Hash {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *BinaryMerkleTree) GetLeafCount() int32 {
	if m != nil {
		return m.LeafCount
	}
	return 0
}

func init() {
	proto.RegisterEnum("aelf.TransactionResultStatus", TransactionResultStatus_name, TransactionResultStatus_value)
	proto.RegisterType((*Transaction)(nil), "aelf.Transaction")
	proto.RegisterType((*StatePath)(nil), "aelf.StatePath")
	proto.RegisterType((*ScopedStatePath)(nil), "aelf.ScopedStatePath")
	proto.RegisterType((*TransactionResult)(nil), "aelf.TransactionResult")
	proto.RegisterType((*LogEvent)(nil), "aelf.LogEvent")
	proto.RegisterType((*SmartContractRegistration)(nil), "aelf.SmartContractRegistration")
	proto.RegisterType((*TransactionExecutingStateSet)(nil), "aelf.TransactionExecutingStateSet")
	proto.RegisterMapType((map[string]bool)(nil), "aelf.TransactionExecutingStateSet.DeletesEntry")
	proto.RegisterMapType((map[string]bool)(nil), "aelf.TransactionExecutingStateSet.ReadsEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "aelf.TransactionExecutingStateSet.WritesEntry")
	proto.RegisterType((*Address)(nil), "aelf.Address")
	proto.RegisterType((*Hash)(nil), "aelf.Hash")
	proto.RegisterType((*SInt32Value)(nil), "aelf.SInt32Value")
	proto.RegisterType((*SInt64Value)(nil), "aelf.SInt64Value")
	proto.RegisterType((*MerklePath)(nil), "aelf.MerklePath")
	proto.RegisterType((*MerklePathNode)(nil), "aelf.MerklePathNode")
	proto.RegisterType((*BinaryMerkleTree)(nil), "aelf.BinaryMerkleTree")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 980 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x6e, 0xe3, 0x36,
	0x10, 0xae, 0xfc, 0xef, 0x91, 0x93, 0x38, 0xc4, 0x22, 0x55, 0x83, 0x4d, 0xd7, 0xd1, 0x1e, 0xd6,
	0xfd, 0x4b, 0xd1, 0x6c, 0x5b, 0x6c, 0xf7, 0xd4, 0xc4, 0x56, 0x5a, 0x01, 0x59, 0x25, 0xa0, 0x8d,
	0x6d, 0x2f, 0x85, 0xc0, 0x48, 0xb4, 0x2d, 0x44, 0x12, 0x0d, 0x92, 0x4e, 0x93, 0x6b, 0x9f, 0x60,
	0xdf, 0xa2, 0x40, 0x9f, 0xa1, 0xe8, 0x8b, 0xf5, 0x52, 0x90, 0x94, 0x63, 0xb9, 0x4e, 0xd1, 0xec,
	0xc9, 0x9c, 0x99, 0x6f, 0x86, 0x9f, 0x66, 0xbe, 0x21, 0x0c, 0x10, 0x31, 0x4e, 0x8f, 0xe6, 0x9c,
	0x49, 0x86, 0x6a, 0x84, 0xa6, 0x13, 0xf7, 0x6f, 0x0b, 0xec, 0x31, 0x27, 0xb9, 0x20, 0x91, 0x4c,
	0x58, 0x8e, 0x0e, 0xa1, 0x36, 0xe1, 0x2c, 0x73, 0xac, 0x9e, 0xd5, 0xb7, 0x8f, 0xb7, 0x8e, 0x14,
	0xe8, 0xe8, 0x24, 0x8e, 0x39, 0x15, 0x02, 0xeb, 0x10, 0x3a, 0x80, 0x8a, 0x64, 0x4e, 0xe5, 0x21,
	0x40, 0x45, 0x32, 0xd4, 0x87, 0x2e, 0xa7, 0x93, 0xf0, 0x2a, 0x65, 0xd1, 0x75, 0x98, 0x2f, 0xb2,
	0x2b, 0xca, 0x9d, 0x6a, 0xcf, 0xea, 0x57, 0xf1, 0x36, 0xa7, 0x93, 0x53, 0xe5, 0x0e, 0xb4, 0x77,
	0x1d, 0x39, 0xe7, 0x74, 0x92, 0xdc, 0x3a, 0xb5, 0x9e, 0xd5, 0xef, 0xac, 0x90, 0x97, 0xda, 0x8b,
	0x9e, 0x81, 0x9d, 0x51, 0x39, 0x63, 0x71, 0x98, 0x93, 0x8c, 0x3a, 0xf5, 0x9e, 0xd5, 0x6f, 0x63,
	0x30, 0xae, 0x80, 0x64, 0x14, 0xed, 0x41, 0x63, 0x4e, 0x38, 0xc9, 0x84, 0xd3, 0xd0, 0x05, 0x0a,
	0x0b, 0x1d, 0x40, 0x5b, 0x24, 0xd3, 0x9c, 0xc8, 0x05, 0xa7, 0xce, 0xbb, 0x40, 0xc7, 0x56, 0x1e,
	0xf7, 0x10, 0xda, 0x23, 0x49, 0x24, 0xbd, 0x24, 0x72, 0x86, 0x9e, 0x40, 0x7d, 0x4e, 0xb8, 0x14,
	0x8e, 0xd5, 0xab, 0xf6, 0xdb, 0xd8, 0x18, 0x6e, 0x08, 0x3b, 0xa3, 0x88, 0xcd, 0x69, 0xbc, 0x02,
	0xbe, 0x80, 0x26, 0x31, 0x1f, 0xfc, 0x70, 0x9b, 0x96, 0x51, 0xf4, 0x1c, 0x6a, 0x73, 0x22, 0x67,
	0x45, 0xaf, 0x76, 0x0c, 0xea, 0xbe, 0x0e, 0xd6, 0x41, 0xf7, 0xaf, 0x0a, 0xec, 0x96, 0x26, 0x80,
	0xa9, 0x58, 0xa4, 0x12, 0x7d, 0x05, 0xdb, 0x72, 0xe5, 0x0c, 0x93, 0xb8, 0xb8, 0x0a, 0x4c, 0x91,
	0x1f, 0x89, 0x98, 0xe1, 0xad, 0x12, 0xc2, 0x8f, 0xd1, 0x37, 0xd0, 0x10, 0x92, 0xc8, 0x85, 0xd0,
	0xf7, 0x6d, 0x1f, 0x1f, 0x18, 0xe8, 0x46, 0xed, 0x91, 0x06, 0xe1, 0x02, 0x8c, 0x5c, 0xa8, 0xa5,
	0x6c, 0x2a, 0x9c, 0x6a, 0xaf, 0xda, 0xb7, 0x8f, 0xb7, 0x4d, 0xd2, 0x39, 0x9b, 0x7a, 0x37, 0x34,
	0x97, 0x58, 0xc7, 0x54, 0x6b, 0xae, 0x52, 0xc6, 0xb2, 0x62, 0x3c, 0xc6, 0x40, 0x87, 0xd0, 0xe1,
	0x54, 0x2e, 0x78, 0x1e, 0xde, 0x90, 0x74, 0x61, 0xc6, 0xd2, 0xc1, 0xb6, 0xf1, 0xbd, 0x55, 0x2e,
	0x05, 0x59, 0x13, 0x42, 0x43, 0x0b, 0xc1, 0xbe, 0x2a, 0xa9, 0xe0, 0x13, 0x00, 0x03, 0x99, 0x11,
	0x31, 0x73, 0x9a, 0x1b, 0x5f, 0xd9, 0xd6, 0x51, 0x75, 0x54, 0x34, 0x28, 0xe7, 0x8c, 0x3b, 0xa0,
	0x05, 0x60, 0x0c, 0xf7, 0x37, 0x0b, 0x5a, 0x4b, 0xbe, 0x8f, 0x9f, 0x0d, 0x82, 0x9a, 0xd6, 0x52,
	0x45, 0x97, 0xd2, 0x67, 0xe4, 0x40, 0x33, 0xc9, 0x63, 0x7a, 0x4b, 0x63, 0xdd, 0x8d, 0x0e, 0x5e,
	0x9a, 0x4a, 0x80, 0xb9, 0x1a, 0x43, 0x11, 0x35, 0x6d, 0x80, 0x9c, 0xe5, 0xbe, 0xf1, 0xb8, 0x7f,
	0x5a, 0xf0, 0xd1, 0x28, 0x23, 0x5c, 0x0e, 0x58, 0x2e, 0x39, 0x89, 0x24, 0xa6, 0xd3, 0x44, 0x48,
	0x4e, 0xf4, 0x56, 0xed, 0x43, 0x2b, 0x22, 0x92, 0x4e, 0x19, 0xbf, 0xd3, 0xb4, 0x76, 0xf1, 0xbd,
	0xad, 0x88, 0x44, 0x2c, 0x36, 0x44, 0x3a, 0x58, 0x9f, 0xd1, 0x0b, 0x68, 0xab, 0x5f, 0xd3, 0x92,
	0xea, 0x46, 0x4b, 0x5a, 0x2a, 0xa8, 0x3b, 0xf2, 0x39, 0xa0, 0x44, 0x84, 0xe2, 0x4e, 0x48, 0x9a,
	0x85, 0x51, 0x71, 0xb5, 0xa6, 0xd7, 0xc2, 0xdd, 0x44, 0x8c, 0x74, 0x60, 0x49, 0x49, 0x7d, 0xdf,
	0x0d, 0xe5, 0x22, 0x61, 0xb9, 0x9e, 0x55, 0x1d, 0x2f, 0x4d, 0xf7, 0xf7, 0x2a, 0x3c, 0x2d, 0x09,
	0xc5, 0xbb, 0xa5, 0xd1, 0x42, 0x26, 0xf9, 0x54, 0x8b, 0x75, 0x44, 0x25, 0x3a, 0x83, 0xc6, 0xaf,
	0x3c, 0x91, 0xd4, 0x6c, 0x87, 0x7d, 0x7c, 0xb4, 0x21, 0xae, 0x8d, 0x9c, 0xa3, 0x9f, 0x74, 0x82,
	0x97, 0x4b, 0x7e, 0x87, 0x8b, 0x6c, 0x34, 0x80, 0x3a, 0xa7, 0x24, 0x56, 0x1a, 0x55, 0x65, 0xbe,
	0x78, 0x44, 0x19, 0xac, 0xf0, 0xa6, 0x8a, 0xc9, 0x45, 0x3e, 0x34, 0x63, 0x9a, 0x52, 0xc5, 0xc6,
	0xa8, 0xf6, 0xcb, 0x47, 0x94, 0x19, 0x9a, 0x0c, 0x53, 0x68, 0x99, 0xbf, 0xff, 0x1d, 0xd8, 0x25,
	0x9a, 0xa8, 0x0b, 0xd5, 0x6b, 0x6a, 0x66, 0xd4, 0xc6, 0xea, 0xa8, 0x34, 0x67, 0xd4, 0x6d, 0xe6,
	0x63, 0x8c, 0xd7, 0x95, 0x57, 0xd6, 0xfe, 0x2b, 0x80, 0x15, 0xb5, 0xff, 0xcb, 0x6c, 0x95, 0x33,
	0x5f, 0x43, 0xa7, 0xcc, 0xe6, 0x7d, 0x72, 0xdd, 0x67, 0xd0, 0x2c, 0xb4, 0xbc, 0x02, 0x59, 0x25,
	0x6a, 0xee, 0x53, 0xa8, 0x2d, 0x97, 0xe5, 0x81, 0xe8, 0x73, 0xb0, 0x47, 0x7e, 0x2e, 0x5f, 0x1e,
	0x9b, 0xfd, 0x5c, 0x03, 0xed, 0xfe, 0x0b, 0xf4, 0xed, 0xd7, 0x0f, 0x80, 0xd0, 0x12, 0x14, 0x00,
	0xbc, 0xa1, 0xfc, 0x3a, 0x35, 0x6f, 0xe2, 0xf7, 0xb0, 0x9b, 0x69, 0x2b, 0x54, 0x8f, 0x5a, 0x98,
	0xb3, 0xf8, 0x5e, 0x2a, 0x4f, 0xcc, 0x70, 0x56, 0xe0, 0x80, 0xc5, 0x14, 0xef, 0x64, 0x6b, 0xb6,
	0x70, 0x7f, 0x81, 0xed, 0x75, 0x08, 0xfa, 0x18, 0x6a, 0x7a, 0x01, 0x36, 0x5f, 0x3e, 0xed, 0x47,
	0x9f, 0x69, 0xf1, 0xa7, 0x74, 0x22, 0xc3, 0x68, 0x96, 0xa4, 0xb1, 0xbe, 0xb5, 0xe8, 0xd8, 0x4e,
	0x22, 0xce, 0xe9, 0x44, 0x0e, 0x94, 0x5f, 0x15, 0x73, 0x05, 0x74, 0x4f, 0x93, 0x9c, 0xf0, 0x3b,
	0x73, 0xc9, 0x98, 0x53, 0x8a, 0x7a, 0x50, 0x2f, 0x13, 0x2d, 0xdf, 0x60, 0x02, 0x8a, 0x02, 0x67,
	0x4c, 0x16, 0x2f, 0xf8, 0x1a, 0x05, 0xe5, 0x47, 0x07, 0x00, 0x29, 0x25, 0x93, 0x30, 0x62, 0x8b,
	0x5c, 0xea, 0x4d, 0xad, 0xe3, 0xb6, 0xf2, 0x0c, 0x94, 0xe3, 0xd3, 0x77, 0x16, 0x7c, 0xf8, 0x1f,
	0xef, 0x2f, 0xda, 0x01, 0x3b, 0xb8, 0x18, 0x87, 0xde, 0xcf, 0xfe, 0x68, 0xec, 0x0d, 0xbb, 0x1f,
	0x20, 0x1b, 0x9a, 0x97, 0x5e, 0x30, 0xf4, 0x83, 0x1f, 0xba, 0x16, 0x02, 0x68, 0x9c, 0x9d, 0xf8,
	0xe7, 0xde, 0xb0, 0x5b, 0x41, 0x6d, 0xa8, 0xbf, 0xf1, 0x03, 0x6f, 0xd8, 0xad, 0xa2, 0x0e, 0xb4,
	0x06, 0x17, 0xc1, 0xd9, 0xb9, 0x3f, 0x18, 0x77, 0x6b, 0x68, 0x0f, 0x50, 0x91, 0x11, 0xbe, 0x3d,
	0x39, 0xf7, 0x87, 0x27, 0x63, 0xff, 0x22, 0xe8, 0xd6, 0xd1, 0x3e, 0xec, 0x05, 0x17, 0x43, 0xaf,
	0xe4, 0x0c, 0x8b, 0x62, 0x8d, 0xd3, 0xad, 0x3f, 0x2a, 0x70, 0xe2, 0xa9, 0x65, 0xb9, 0x9b, 0x53,
	0x71, 0xd5, 0xd0, 0x7f, 0x06, 0x5e, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x26, 0x28, 0x35,
	0x1a, 0x08, 0x00, 0x00,
}
